apiVersion: apps/v1
kind: Deployment
metadata:
  name: peanut-backstage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: peanut-backstage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: peanut-backstage
    spec:
      containers:
      - name: peanut-backstage
        image: bigkevmcd/peanut-backstage:latest
        env:
        - name: PORT
          value: "9080"
      serviceAccountName: peanut-backstage
---
apiVersion: v1
kind: Service
metadata:
  name: peanut-backstage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: peanut-backstage
  ports:
    - protocol: TCP
      port: 9080
